<?php

declare(strict_types=1);

namespace FalconERP\Skeleton\Enums\Fiscal;

enum NatureOperationDescriptionEnum: string
{
    case DESCRIPTION_VENDA_DE_PRODUCAO_DO_ESTABELECIMENTO       = 'VENDA DE PRODUCAO DO ESTABELECIMENTO';
    case DESCRIPTION_VENDA_DE_MERCADORIA_ADQUIRIDA_DE_TERCEIROS = 'VENDA DE MERCADORIA ADQUIRIDA DE TERCEIROS';
    case DESCRIPTION_DEVOLUCAO_DE_VENDA                         = 'DEVOLUCAO DE VENDA';
    case DESCRIPTION_TRANSFERENCIA_ENTRE_FILIAIS                = 'TRANSFERENCIA ENTRE FILIAIS';
    case DESCRIPTION_CONSIGNACAO_MERCANTIL                      = 'CONSIGNACAO MERCANTIL';
    case DESCRIPTION_REMESSA_PARA_INDUSTRIALIZACAO              = 'REMESSA PARA INDUSTRIALIZACAO';
    case DESCRIPTION_RETORNO_DE_INDUSTRIALIZACAO                = 'RETORNO DE INDUSTRIALIZACAO';
    case DESCRIPTION_IMPORTACAO_DE_MERCADORIAS                  = 'IMPORTACAO DE MERCADORIAS';
    case DESCRIPTION_EXPORTACAO_DE_MERCADORIAS                  = 'EXPORTACAO DE MERCADORIAS';
    case DESCRIPTION_BONIFICACAO_OU_DOACAO                      = 'BONIFICACAO OU DOACAO';
    case DESCRIPTION_REMESSA_PARA_DEMONSTRACAO                  = 'REMESSA PARA DEMONSTRACAO';
    case DESCRIPTION_REMESSA_PARA_CONSERTO_OU_REPARACAO         = 'REMESSA PARA CONSERTO OU REPARACAO';
    case DESCRIPTION_COMPRA_PARA_REVENDA                        = 'COMPRA PARA REVENDA';
    case DESCRIPTION_COMPRA_PARA_USO_E_CONSUMO                  = 'COMPRA PARA USO E CONSUMO';
    case DESCRIPTION_COMPRA_DE_ATIVO_IMOBILIZADO                = 'COMPRA DE ATIVO IMOBILIZADO';
    case DESCRIPTION_DEVOLUCAO_DE_COMPRA                        = 'DEVOLUCAO DE COMPRA';
    case DESCRIPTION_REMESSA_PARA_ARMAZENAGEM                   = 'REMESSA PARA ARMAZENAGEM';
    case DESCRIPTION_VENDA_PARA_ENTREGA_FUTURA                  = 'VENDA PARA ENTREGA FUTURA';
    case DESCRIPTION_REMESSA_PARA_EXPORTACAO                    = 'REMESSA PARA EXPORTACAO';
    case DESCRIPTION_VENDA_COM_SUBSTITUICAO_TRIBUTARIA          = 'VENDA COM SUBSTITUICAO TRIBUTARIA';

  /*   public function type(): string
    {
        return match ($this) {
            self::DESCRIPTION_VENDA_DE_PRODUCAO_DO_ESTABELECIMENTO,
            self::DESCRIPTION_VENDA_DE_MERCADORIA_ADQUIRIDA_DE_TERCEIROS,
            self::DESCRIPTION_DEVOLUCAO_DE_VENDA,
            self::DESCRIPTION_TRANSFERENCIA_ENTRE_FILIAIS,
            self::DESCRIPTION_CONSIGNACAO_MERCANTIL,
            self::DESCRIPTION_REMESSA_PARA_INDUSTRIALIZACAO,
            self::DESCRIPTION_RETORNO_DE_INDUSTRIALIZACAO,
            self::DESCRIPTION_IMPORTACAO_DE_MERCADORIAS,
            self::DESCRIPTION_EXPORTACAO_DE_MERCADORIAS,
            self::DESCRIPTION_BONIFICACAO_OU_DOACAO,
            self::DESCRIPTION_REMESSA_PARA_DEMONSTRACAO,
            self::DESCRIPTION_REMESSA_PARA_CONSERTO_OU_REPARACAO,
            self::DESCRIPTION_COMPRA_PARA_REVENDA,
            self::DESCRIPTION_COMPRA_PARA_USO_E_CONSUMO,
            self::DESCRIPTION_COMPRA_DE_ATIVO_IMOBILIZADO,
            self::DESCRIPTION_DEVOLUCAO_DE_COMPRA,
            self::DESCRIPTION_REMESSA_PARA_ARMAZENAGEM,
            self::DESCRIPTION_VENDA_PARA_ENTREGA_FUTURA,
            self::DESCRIPTION_REMESSA_PARA_EXPORTACAO,
            self::DESCRIPTION_VENDA_COM_SUBSTITUICAO_TRIBUTARIA => '0',
        };
    } */

  /*   public function cfop(): string
    {
        return match ($this) {
            self::DESCRIPTION_VENDA_DE_PRODUCAO_DO_ESTABELECIMENTO       => '5101',
            self::DESCRIPTION_VENDA_DE_MERCADORIA_ADQUIRIDA_DE_TERCEIROS => '5102',
            self::DESCRIPTION_DEVOLUCAO_DE_VENDA                         => '5103',
            self::DESCRIPTION_TRANSFERENCIA_ENTRE_FILIAIS                => '5104',
            self::DESCRIPTION_CONSIGNACAO_MERCANTIL                      => '5105',
            self::DESCRIPTION_REMESSA_PARA_INDUSTRIALIZACAO              => '5106',
            self::DESCRIPTION_RETORNO_DE_INDUSTRIALIZACAO                => '5107',
            self::DESCRIPTION_IMPORTACAO_DE_MERCADORIAS                  => '5108',
            self::DESCRIPTION_EXPORTACAO_DE_MERCADORIAS                  => '5109',
            self::DESCRIPTION_BONIFICACAO_OU_DOACAO                      => '5110',
            self::DESCRIPTION_REMESSA_PARA_DEMONSTRACAO                  => '5111',
            self::DESCRIPTION_REMESSA_PARA_CONSERTO_OU_REPARACAO         => '5112',
            self::DESCRIPTION_COMPRA_PARA_REVENDA                        => '5113',
            self::DESCRIPTION_COMPRA_PARA_USO_E_CONSUMO                  => '5114',
            self::DESCRIPTION_COMPRA_DE_ATIVO_IMOBILIZADO                => '5115',
            self::DESCRIPTION_DEVOLUCAO_DE_COMPRA                        => '5116',
            self::DESCRIPTION_REMESSA_PARA_ARMAZENAGEM                   => '5117',
            self::DESCRIPTION_VENDA_PARA_ENTREGA_FUTURA                  => '5118',
            self::DESCRIPTION_REMESSA_PARA_EXPORTACAO                    => '5119',
            self::DESCRIPTION_VENDA_COM_SUBSTITUICAO_TRIBUTARIA          => '5120',
        };
    } */
}
